version: "3.9"
services:
  api:
    container_name: nasdaq-api
    ports:
      - "3000:${PORT}"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_URI: root:mysql@tcp(mysql:3306)/nasdaq-mysql?parseTime=true
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nasdaq-network
  mysql:
    container_name: nasdaq-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: nasdaq-mysql
      MYSQL_ROOT_PASSWORD: mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - nasdaq-network
  migrate:
    image: migrate/migrate:v4.15.2
    profiles: [ "tools" ]
    volumes:
      - ./database/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "mysql://root:mysql@tcp(mysql:3306)/nasdaq-mysql?parseTime=true"
      ]
    command: [ "up" ]
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - nasdaq-network
networks:
  nasdaq-network:
    driver: bridge
