DROP TABLE IF EXISTS cat CASCADE;
DROP TABLE IF EXISTS `module`;
DROP TABLE IF EXISTS `content`;
DROP TABLE IF EXISTS `company_info`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `deposit_withdraw`;
DROP TABLE IF EXISTS `card_info`;
DROP TABLE IF EXISTS `oders`;
DROP TABLE IF EXISTS `finance`;
DROP TABLE IF EXISTS `package_finance`;
DROP TABLE IF EXISTS `package`;


